application: kmlcircle
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /circle
  script: main.py

- url: /
  static_files: static/index.html
  upload: static/index.html

