application: kmlcircle
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /favicon\.png
  static_files: static/favicon.png
  upload: static/favicon.png
  mime_type: image/png

- url: /icon64\.png
  static_files: static/icon64.png
  upload: static/icon64.png
  mime_type: image/png

- url: .*
  script: main.py
